version: "3"
services:
  mongo:
    image: mongo:3.4.19
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
  
  mongo-express:
    image: mongo-express:0.49.0
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    ports:
      - 8081:8081
    links:
      - mongo
